name: packerbuild

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout Code repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Set up environment variables
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres" >> $GITHUB_ENV

      - name: Run FastAPI application
        run: uvicorn main:application --host 0.0.0.0 --port 8000 &

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Integration Tests
        run: pytest main_test.py

  packerbuild:
    name: Packerbuild
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer

      - name: Initialize packer
        run: packer init packer

      - name: Build Packer image
        run: packer build packer

    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      PKR_VAR_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      PKR_VAR_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PKR_VAR_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      PKR_VAR_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      PKR_VAR_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
